project:
  type: website
  output-dir: docs

website:
  title: "RPS.bot"
  page-footer: "\xA9 2024 Overbet.ai. All rights reserved."
  open-graph: true
  google-analytics: G-6GK6C5LZSG
  favicon: ./assets/logo.png
  navbar: 
    logo: ./assets/logo.png
    background: dark
    right: 
      - text: "About"
        href: about.qmd
      - text: "Overbet.ai"
        href: https://overbet.ai
    tools: 
      - icon: discord
        href: https://discord.gg/KZQK2xN8Da
      - icon: mailbox2-flag
        href: https://overbetai.substack.com/
      - icon: github
        href: https://github.com/overbetai/cardstocode
  sidebar: 
    style: "docked"
    background: light
    contents:
        - text: "Home"
          href: "index.qmd"
        - text: "Intro to RPS"
          href: "intro.qmd"
        - text: "Intro to Opponent Modeling"
          href: "rpsom.qmd"
        - text: "Intro to Opponent Modeling in Code"
          href: "rpsomc.qmd"
        - text: "Opponent Modeling Tutorial"
          href: "rpsomtutorial.qmd"
        - text: "RPS Bot Challenge"
          href: "rpsbotchallenge.qmd"

format:
  html:
    theme: 
      - cerulean
    grid:
      sidebar-width: 300px
    math: true 
    html-math-method: katex
    toc: true
    toc-expand: true